### ISSUE TITLE
Loading pretrained model fails due to memory error

### ISSUE THREAD

**Issue by mangleddata** [uber/ludwig#642]
I have a trained model on a dataset A and am trying to load the model as initialization on a different dataset B. Both A and B are of same size and the model file is exactly the same. However, the loading seems to fail due to memory issue [done via -mlp ${INIT_MODEL_PATH}  to ludwig train command ]. This seems strange because I would've though the loader should've simply worked since the dataset sizes are same. Any idea why it may be happening ? Does preloading this way needs twice as much memory for example ? The errors look like below

E tensorflow/stream_executor/cuda/cuda_driver.cc:828] failed to allocate 1.32G (1419129856 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

Are there any workarounds possible ?

**Comment by w4nderlust** [comment]
@mangleddata thanks for posting this. In order to debug we need more information. Specifically, we need a way to reproduce the problem, be it a model_definition.yaml + data + command or a python script or notebook. If you can't share your data there's a script that synthesizes data for you in `data/dataset_synthesyzer.py`. Anyway, being it a tensorflow memory allocation problem, it's likely a model problem and not a dataset problem. In most cases the size of the dataset does not impact the size of the model.

**Comment by mangleddata** [comment]
Please take a look into https://github.com/mangleddata/repro_ludwig
The data is randomly created, so wont make sense. But you should be able to reproduce. Perhaps, you could take a look into the scripts to see if I am doing something basic incorrectly. 

Thanks for looking into it.

**Comment by mangleddata** [comment]
Something I just found out. If I initialize and run without a distributed trainer [so ```horovodrun -np 1 --stall-check-shutdown-time-seconds 120 ludwig ...```], it seems to work.

**Comment by w4nderlust** [comment]
> Something I just found out. If I initialize from a previous model and run without a distributed trainer [so `horovodrun -np 1 --stall-check-shutdown-time-seconds 120 ludwig ...`], it seems to work.

Thank you, this is pretty valuable for us to reduce the scope and identify where the problem lies. Will look into it and keep you psoted.

**Comment by w4nderlust** [comment]
An update on this issue @mangleddata .
I was able to run your code, thank you for being really through with it, it helps a lot.
Unfortunately I was not able to replicate the error, most likely because either my machine has more RAM or my GPUs have more VRAM than yours.
Anyway, while running your rerun script I noticed a weird thing when using horovodrun.
```
[1,0]<stdout>:╒══════════╕
[1,0]<stdout>:│ TRAINING │
[1,0]<stdout>:╘══════════╛
[1,0]<stdout>:
[1,0]<stderr>:2020-03-05 14:07:50.483284: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,0]<stderr>:2020-03-05 14:07:50.514970: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494365000 Hz
[1,0]<stderr>:2020-03-05 14:07:50.515261: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x18ffe050 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,0]<stderr>:2020-03-05 14:07:50.515284: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,0]<stderr>:2020-03-05 14:07:50.519618: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[1,0]<stderr>:2020-03-05 14:07:50.927518: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x61600c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
[1,0]<stderr>:2020-03-05 14:07:50.927561: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
[1,0]<stderr>:2020-03-05 14:07:50.927571: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
[1,0]<stderr>:2020-03-05 14:07:50.929271: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
[1,0]<stderr>:name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
[1,0]<stderr>:pciBusID: 0000:02:00.0
[1,0]<stderr>:2020-03-05 14:07:50.930630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 1 with properties: 
[1,0]<stderr>:name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
[1,0]<stderr>:pciBusID: 0000:03:00.0
[1,0]<stderr>:2020-03-05 14:07:50.931131: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.933364: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.935192: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.935716: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.938355: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.939922: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.943993: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
[1,0]<stderr>:2020-03-05 14:07:50.947199: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0, 1
[1,0]<stderr>:2020-03-05 14:07:50.947257: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,0]<stderr>:2020-03-05 14:07:50.949328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,0]<stderr>:2020-03-05 14:07:50.949344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 1 
[1,0]<stderr>:2020-03-05 14:07:50.949350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N N 
[1,0]<stderr>:2020-03-05 14:07:50.949354: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 1:   N N 
[1,0]<stderr>:2020-03-05 14:07:50.951589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8565 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
[1,0]<stderr>:2020-03-05 14:07:50.953408: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10311 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
[1,1]<stderr>:2020-03-05 14:07:52.543080: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,1]<stderr>:2020-03-05 14:07:52.571127: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494365000 Hz
[1,1]<stderr>:2020-03-05 14:07:52.571545: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x1c3d7eb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,1]<stderr>:2020-03-05 14:07:52.571572: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,1]<stderr>:2020-03-05 14:07:52.575486: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[1,1]<stderr>:2020-03-05 14:07:52.764596: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5273260 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
[1,1]<stderr>:2020-03-05 14:07:52.764649: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
[1,1]<stderr>:2020-03-05 14:07:52.764662: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): GeForce RTX 2080 Ti, Compute Capability 7.5
[1,1]<stderr>:2020-03-05 14:07:52.766768: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
[1,1]<stderr>:name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
[1,1]<stderr>:pciBusID: 0000:02:00.0
[1,1]<stderr>:2020-03-05 14:07:52.768520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 1 with properties: 
[1,1]<stderr>:name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
[1,1]<stderr>:pciBusID: 0000:03:00.0
[1,1]<stderr>:2020-03-05 14:07:52.769013: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.771443: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.772868: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.773229: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.775173: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.776662: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.781237: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
[1,1]<stderr>:2020-03-05 14:07:52.784516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0, 1
[1,1]<stderr>:2020-03-05 14:07:52.784575: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,1]<stderr>:2020-03-05 14:07:52.786729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,1]<stderr>:2020-03-05 14:07:52.786747: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 1 
[1,1]<stderr>:2020-03-05 14:07:52.786754: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N N 
[1,1]<stderr>:2020-03-05 14:07:52.786758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 1:   N N 
[1,1]<stderr>:2020-03-05 14:07:52.789056: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8171 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
[1,1]<stderr>:2020-03-05 14:07:52.790358: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10164 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)
```
As you can see both processes are trying to use both GPUs, while when training the first time with horovod each process was using one GPU:
```
[1,0]<stdout>:╒══════════╕
[1,0]<stdout>:│ TRAINING │
[1,0]<stdout>:╘══════════╛
[1,0]<stdout>:
[1,0]<stderr>:2020-03-05 14:01:28.909995: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,0]<stderr>:2020-03-05 14:01:28.939007: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494365000 Hz
[1,0]<stderr>:2020-03-05 14:01:28.939324: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x56d54d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,0]<stderr>:2020-03-05 14:01:28.939352: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,0]<stderr>:2020-03-05 14:01:28.942797: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[1,0]<stderr>:2020-03-05 14:01:29.219551: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xf398c70 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
[1,0]<stderr>:2020-03-05 14:01:29.219592: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
[1,0]<stderr>:2020-03-05 14:01:29.221195: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
[1,0]<stderr>:name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
[1,0]<stderr>:pciBusID: 0000:02:00.0
[1,0]<stderr>:2020-03-05 14:01:29.222702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.263498: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.279116: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.287012: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.331148: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.358297: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.430127: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
[1,0]<stderr>:2020-03-05 14:01:29.432621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
[1,0]<stderr>:2020-03-05 14:01:29.432714: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,0]<stderr>:2020-03-05 14:01:29.436324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,0]<stderr>:2020-03-05 14:01:29.436352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
[1,0]<stderr>:2020-03-05 14:01:29.436365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
[1,0]<stderr>:2020-03-05 14:01:29.438562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8552 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2080 Ti, pci bus id: 0000:02:00.0, compute capability: 7.5)
[1,1]<stderr>:2020-03-05 14:01:30.694960: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
[1,1]<stderr>:2020-03-05 14:01:30.723104: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2494365000 Hz
[1,1]<stderr>:2020-03-05 14:01:30.723415: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5063230 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
[1,1]<stderr>:2020-03-05 14:01:30.723440: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[1,1]<stderr>:2020-03-05 14:01:30.727007: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
[1,1]<stderr>:2020-03-05 14:01:30.885130: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5184550 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
[1,1]<stderr>:2020-03-05 14:01:30.885178: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce RTX 2080 Ti, Compute Capability 7.5
[1,1]<stderr>:2020-03-05 14:01:30.887298: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
[1,1]<stderr>:name: GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
[1,1]<stderr>:pciBusID: 0000:03:00.0
[1,1]<stderr>:2020-03-05 14:01:30.887833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.890398: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.892588: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.893213: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.896081: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.898183: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.901979: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
[1,1]<stderr>:2020-03-05 14:01:30.903680: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 1
[1,1]<stderr>:2020-03-05 14:01:30.903744: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
[1,1]<stderr>:2020-03-05 14:01:30.905820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
[1,1]<stderr>:2020-03-05 14:01:30.905835: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      1 
[1,1]<stderr>:2020-03-05 14:01:30.905852: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 1:   N 
[1,1]<stderr>:2020-03-05 14:01:30.907516: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10311 MB memory) -> physical GPU (device: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:03:00.0, compute capability: 7.5)

```
So my current suspicion is that when loading for some reason the GPU assignment gets mixed up.
I will inspect more and keep you posted if that's the case and if I can find a solution.

One minor comment: your model is pretty complicated with dependencies between different outputs and heads with their own weights and different datatypes as inputs, it's really cool! These are the kind of things I would love users to be able to do with Ludwig :) I'm curious what it is actually used for, we can chat privately about it if you prefer. Anyway, there's one minor problem with the model definition. you define validation_field and validation_measure for each output feature, while they are parameters of the training section of the yaml file. Right now they are ignored. The logic is: when deciding if to do an early stopping, I have to keep track of a specific number to see if it improves, and that number can be any of the validation "cells" that are printed at the end of each epoch or all the features, so you have to decide which of the different output features to keep track of and which measure (loss, accuracy, etc.) and there's also a combined feature in which the loss is the weighted sum of all others. So you have to pick one of them fundamentally, if you don't know which one, pick `validation_field: combined` and `validation_measure: loss`.

**Comment by mangleddata** [comment]
Thanks for looking into this. The fix you made did fix the load issue. I am able initialize the model from previous model results and it works great! One issue though, something got broke if I simply did a reinstall - not sure if some dependencies are messed up. So I had to manually merge the changes and that's good enough for me. I understand you may not have time, but it would be great if someone could build a docker image or some cloud image with major versions. That way all the prereq would be baked in and it would be much simpler to launch.

As for the complex model, it's a hobby project and I would be happy to chat more. It is more complex than what it needs to be, but it has been lot of fun and I am still at it during my free time. Please reach out to mangled.data@gmail.com and I will explain in detail what I am trying to do.

**Comment by w4nderlust** [comment]
What got broke when you reinstall? Can you try to start a fresh venv and see if that solves the problem?

Regarding the docker, there is a dockerfile in the repo, that doesn't work for you?

Will reach out to you regarding the project, I'm curious.
